spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  config:
    import: optional:application-secret.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
    open-in-view: false
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash

logging:
  level:
    root: info