spring:
  config:
    import: optional:file:.env[.properties]

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESSTOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESHTOKEN_EXPIRATION}