spring:
  datasource:
    url: jdbc:h2:mem:its_here_db;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: on
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.spring: debug

storage:
  type: local
  local:
    root-path: ./storage