spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 개발 중이므로 update(추후에 validate로 수정 예정)
    show-sql: false

storage:
  type: s3